import './style.css'
import { SettingsManager } from './settings.js'
import { UIManager } from './ui.js'
import { EpubReader } from './reader.js'
import { StorageManager } from './storage.js'
import { MobiConverter } from './mobi-converter.js'

document.addEventListener('DOMContentLoaded', async () => {
    const settingsManager = new SettingsManager()
    const uiManager = new UIManager(settingsManager)
    const reader = new EpubReader(settingsManager, uiManager)
    const storageManager = new StorageManager()
    const mobiConverter = new MobiConverter()

    // Core Logic
    const loadBook = async (bookId) => {
        try {
            uiManager.showLoading()
            const bookData = await storageManager.getBook(bookId)
            if (bookData) {
                uiManager.hideLibrary()
                uiManager.updateTitle(bookData.metadata.name)
                // We need to wait for UI transition before rendering
                setTimeout(async () => {
                    await reader.load(bookData.file)
                    await storageManager.setLastOpened(bookId)
                    refreshHistory(bookId)
                }, 100)
            } else {
                uiManager.showError('Book not found')
                loadLibrary()
            }
        } catch (e) {
            console.error("Failed to load book:", e)
            uiManager.showError("Failed to load book.")
            loadLibrary()
        }
    }

    const loadLibrary = async () => {
        const books = await storageManager.getAllBooks()
        uiManager.showLibrary(books,
            // On Select
            (bookId) => loadBook(bookId),
            // On Delete
            async (bookId) => {
                await storageManager.deleteBook(bookId)
                loadLibrary() // Reload list
            }
        )
    }

    const refreshHistory = async (bookId) => {
        const history = await storageManager.getHistory(bookId)
        uiManager.renderHistory(history)
    }

    uiManager.onDeleteHistory = async (historyId) => {
        await storageManager.deleteExplanation(historyId)
        const lastBookId = await storageManager.getLastOpened()
        if (lastBookId) refreshHistory(lastBookId)
    }

    // Overwrite showExplanationModal to include saving
    const originalShowExplanation = uiManager.showExplanationModal.bind(uiManager)
    uiManager.showExplanationModal = async (text) => {
        const bookId = await storageManager.getLastOpened()

        // We need to wait for the explanation to be generated by the original method
        // But the original method is async and private-ish logic.
        // Let's optimize: UIManager usually handles the call. Let's wrap the logic there or here.
        // Better: Update UIManager directly to accept a callback or use an event.
        // For now, let's just use the current context in main.js

        uiManager.explanationModal.classList.remove('hidden')
        uiManager.explanationSource.textContent = text
        uiManager.explanationSource.classList.remove('hidden')
        uiManager.chatMessages.innerHTML = ''
        uiManager.appendMessage("Explain this text", 'user')
        const loadingId = uiManager.appendLoadingMessage()

        try {
            const explanation = await uiManager.geminiService.startChat(text)
            uiManager.removeMessage(loadingId)
            uiManager.appendMessage(explanation, 'ai')

            // Save to history
            if (bookId) {
                await storageManager.saveExplanation(bookId, text, explanation)
                refreshHistory(bookId)
            }
        } catch (error) {
            uiManager.removeMessage(loadingId)
            uiManager.appendMessage(`Error: ${error.message}`, 'ai')
        }
    }

    // Initialize
    try {
        const lastBookId = await storageManager.getLastOpened()
        if (lastBookId) {
            await loadBook(lastBookId)
        } else {
            loadLibrary()
        }
    } catch (e) {
        console.error("Failed to load last session:", e)
        loadLibrary() // Fallback
    }

    // Event Listeners

    // Logo Click -> Library
    const logo = document.querySelector('.logo')
    if (logo) {
        logo.addEventListener('click', () => {
            loadLibrary()
        })
    }

    // Header File Upload (keep existing one too)
    const epubUpload = document.getElementById('epub-upload')
    if (epubUpload) {
        epubUpload.accept = ".epub,.azw3,.mobi"
        epubUpload.addEventListener('change', async (e) => {
            const file = e.target.files[0]
            if (!file) return

            try {
                uiManager.showLoading()
                let bookFile = file
                let fileName = file.name

                // Handle Kindle formats
                const isKindle = fileName.toLowerCase().endsWith('.azw3') || fileName.toLowerCase().endsWith('.mobi')
                if (isKindle) {
                    uiManager.updateTitle('Converting Kindle file...')
                    bookFile = await mobiConverter.convert(file)
                    // Ensure name ends with .epub for future preservation if needed, 
                    // though storage manager handles it by ID.
                    fileName = fileName.replace(/\.(azw3|mobi)$/i, '.epub')
                }

                // Save to storage
                const bookId = await storageManager.saveBook(bookFile, fileName)
                await loadBook(bookId)
                // Clear input
                e.target.value = ''
            } catch (err) {
                console.error("Error processing book:", err)
                uiManager.showError("Failed to process book file. It might be DRM protected or invalid.")
            } finally {
                uiManager.hideLoading()
            }
        })
    }

    // Search Logic
    const searchInput = document.getElementById('search-input')
    const closeSearch = document.getElementById('close-search')
    let searchTimeout = null

    if (searchInput) {
        searchInput.addEventListener('input', (e) => {
            clearTimeout(searchTimeout)
            const query = e.target.value.trim()
            if (query.length < 3) {
                uiManager.searchResults.innerHTML = '<p class="search-empty">Type at least 3 characters...</p>'
                reader.clearHighlights()
                return
            }

            searchTimeout = setTimeout(async () => {
                uiManager.searchResults.innerHTML = '<div class="search-empty">Searching...</div>'
                const results = await reader.search(query)

                // Clear and render new highlights
                reader.clearHighlights()
                reader.renderHighlights(results)

                uiManager.renderSearchResults(results, (cfi) => {
                    reader.rendition.display(cfi)
                })
            }, 500)
        })

        // Handle native "X" search-clear button in some browsers
        searchInput.addEventListener('search', (e) => {
            if (e.target.value === '') {
                uiManager.searchResults.innerHTML = '<p class="search-empty">Type to start searching...</p>'
                reader.clearHighlights()
            }
        })
    }

    if (closeSearch) {
        closeSearch.addEventListener('click', () => {
            reader.clearHighlights()
        })
    }

    uiManager.onToggleSearch = (isOpen) => {
        if (!isOpen) {
            reader.clearHighlights()
        }
    }
})
